[build]
  base = "dermaelixir"
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_VERSION = "0.145.0"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"

[context.branch-deploy]
  command = "hugo --environment production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200