baseURL: http://localhost:1313/
languageCode: en-us
title: Derma Elixir
theme: DermaMunu

disableKinds: 
  - "taxonomy"
  - "term"

disableHugoGeneratorInject: true  # Disable the Hugo generator tag in the HTML head


 # Define the permalink structure
permalinks:
  about: "/about/"
  treatments: "/treatments/"
  
# Enable the use of assets (CSS, images, fonts) stored in the "assets" folder
params:
  assetsDir: "assets"
  homeInfoParams:
    Title: "Derma Elixir"
    Subtitle: "Aesthetic Clinic"
    Content: "Derma Elixir is a professional aesthetic clinic based in the ealing."
 

  websiteDescription: "Derma Elixir is a professional aesthetic clinic based in the ealing."
  websiteKeywords: "aesthetic, clinic, ealing, derma, elixir"
  websiteAuthor: "Derma Elixir"
  websiteCopyright: "Derma Elixir"
  websiteLanguage: "en"
  websiteRobots: "index, follow"
  websiteThemeColor: "#ffffff"
  websiteTwitterCard: "summary"
  websiteTwitterSite: "@DermaElixir"
  websiteTwitterCreator: "@DermaElixir"
  websiteOpenGraphType: "website"
  websiteOpenGraphTitle: "Derma Elixir"
  websiteOpenGraphDescription: "Derma Elixir is a professional aesthetic clinic based in the ealing."
  websiteOpenGraphImage: "og-image.png"
  websiteOpenGraphImageAlt: "Derma Elixir Open Graph Image"
  websiteOpenGraphUrl: "https://dermaelixir.co.uk/"
  websiteOpenGraphSiteName: "Derma Elixir"
  websiteOpenGraphLocale: "en_US"
  websiteOpenGraphArticleAuthor: "Derma Elixir"
  websiteOpenGraphArticlePublisher: "Derma Elixir"
  websiteOpenGraphArticleModifiedTime: "2021-01-01T00:00:00Z"
  websiteOpenGraphArticlePublishedTime: "2021-01-01T00:00:00Z"
  websiteOpenGraphArticleSection: "Aesthetic Clinic"
  websiteOpenGraphArticleTag: "aesthetic, clinic, ealing, derma, elixir"
  enableRobotsTXT: true
  enableSitemapXML: true